version: '3.8'

services:
  php-apache-environment:
    container_name: php7.0-apache
    build:
      context: ./www
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8082:80
volumes:
  mysql:
