version: '3.8'
services:
  php-apache-environment:
    container_name: php8.1-apache
    build:
      context: ./www
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./www:/var/www/html/
    ports:
      - 8081:80
  db:
    container_name: db-mysql8.0
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_mysql8
      MYSQL_PASSWORD: root
    ports:
      - '8806:3306'
